// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA88DxPGk8LlwzPssJp1mJk6x3F1y-nztI',
    appId: '1:677763459641:web:81119dcf3cac0da89f7be8',
    messagingSenderId: '677763459641',
    projectId: 'ticket-tracking-app',
    authDomain: 'ticket-tracking-app.firebaseapp.com',
    storageBucket: 'ticket-tracking-app.appspot.com',
    measurementId: 'G-4P0EPZFTPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7L2e32PmnjlZXgXUz8_M-YSEszeTONjY',
    appId: '1:677763459641:android:a37719f975db83949f7be8',
    messagingSenderId: '677763459641',
    projectId: 'ticket-tracking-app',
    storageBucket: 'ticket-tracking-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvnBFdyncp1e7bd_QIvirnyB6ctGurLI0',
    appId: '1:677763459641:ios:963af08cbb32d5619f7be8',
    messagingSenderId: '677763459641',
    projectId: 'ticket-tracking-app',
    storageBucket: 'ticket-tracking-app.appspot.com',
    iosBundleId: 'com.example.machineTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvnBFdyncp1e7bd_QIvirnyB6ctGurLI0',
    appId: '1:677763459641:ios:ec85d337359294f69f7be8',
    messagingSenderId: '677763459641',
    projectId: 'ticket-tracking-app',
    storageBucket: 'ticket-tracking-app.appspot.com',
    iosBundleId: 'com.example.machineTest1.RunnerTests',
  );
}
